version: '3.1'

services:
    # for local development of cFS
    dev:
        container_name: dev
        restart: "no" # let us manually restart if cFS crashes
        networks:
            - sat-link # network for our ground station to connect to
        environment:
            O: build-dev # folder to install to
            BUILDTYPE: "debug"
            OMIT_DEPRECATED: "true" # don't rely on depreciated cFE features
            SIMULATION: native # use native_osconfig.cmake
            BUILD: cpu1 # the name of the bundle
        cap_add: 
            - CAP_SYS_RESOURCE # give the runtime adequate resources
        build: # select the correct dockerfile
            context: ./dockerfiles
            dockerfile: ubuntu.Dockerfile
        volumes:
          - ./:/cfs # mount the code into the docker container

    # for the ground station
    yamcs:
        # select the right container and build
        build:
            context: ./dockerfiles
            dockerfile: yamcs.Dockerfile
        hostname: yamcs
        container_name: yamcs
        env_file: .env # load an environment file
        command: "/run_yamcs.sh" # run the maven project
        volumes: # map the yamcs directory into the container
            - ./yamcs:/yamcs
            - ./dockerfiles/run_yamcs.sh:/run_yamcs.sh
        networks: # connect it to the same network as cFS
            - sat-link
        ports: # expose the required ports
            - "8090:8090"
            - "${TO_PORT}:${TO_PORT}/udp"
            - "${CI_PORT}:${CI_PORT}"

# definition of the aforementioned network
networks:
    sat-link:
        driver: bridge